# -*- coding: utf-8 -*-
from __future__ import annotations

app_name = "devp_custom"
app_title = "Devp Custom"
app_publisher = "Mradul Mishra"
app_description = "Devp Custom"
app_email = "mradulmishra010@gmail.com"
app_license = "mit"

fixtures = ["Custom Field"]

# ---------------------------------------------------------------------
# Client Scripts
# ---------------------------------------------------------------------
doctype_js = {
    "Item": "public/js/item_client.js",
    "Sales Order": [
        "public/js/sales_order_item.js",
        "public/js/mapping_on_rate_change.js",
    ],
    "Quotation": [
        "public/js/quotation_item_last_prices.js",
        "public/js/mapping_on_rate_change.js",
    ],
    "Sales Invoice": [
        "public/js/sales_invoice_item.js",
        "public/js/sales_invoice_batch_dates.js",
        "public/js/sales_invoice_batch_size.js",
        "public/js/mapping_on_rate_change.js",
    ],
}

# Also include core JS globally if you need it on every desk page
app_include_js = [
    "public/js/sales_invoice_item.js",
]

# ---------------------------------------------------------------------
# Server Hooks
# ---------------------------------------------------------------------
doc_events = {
    # Item code auto-generation
    "Item": {
        "before_insert": "devp_custom.api.assign_item_code_before_insert",
        "on_submit": "devp_custom.api.auto_set_item_code_on_submit",
    },

    # Line-level overrides
    "Sales Invoice Item": {
        "validate": "devp_custom.overrides.sales_invoice_item.calculate_amount",
    },

    # Batch-size warning (non-blocking) on SI validate
    "Work Order": {
        "validate": "devp_custom.api.validate_work_order_batch_size",
    },
    "Sales Invoice": {
        "validate": "devp_custom.api.validate_sales_invoice_batch_size",
        "before_save": "devp_custom.api.apply_customer_item_names",
        # Availability control (affects stock only when update_stock=1)
        "before_submit": "devp_custom.api.validate_available_qty",
        "on_submit": "devp_custom.api.consume_available_qty",
        "on_cancel": "devp_custom.api.revert_available_qty",
    },

    # Apply customer item names
    "Sales Order": {
        "before_save": "devp_custom.api.apply_customer_item_names",
    },
    "Quotation": {
        "before_save": "devp_custom.api.apply_customer_item_names",
    },

    # Delivery Note moves stock, so always apply availability control
    "Delivery Note": {
        "before_submit": "devp_custom.api.validate_available_qty",
        "on_submit": "devp_custom.api.consume_available_qty",
        "on_cancel": "devp_custom.api.revert_available_qty",
    },
}

# (Leave the rest of the autogenerated hook placeholders commented)
